version: "2"
services:
  app:
    build: ./app
    volumes:
      - ./app/data/files:/arozos/src/files
      - ./app/data/tmp:/arozos/src/tmp
      - ./app/data/system:/arozos/src/system
    ports:
      - 8888:80
    restart: always
