version: "2.4"
services:
  x64:
    platform: linux/amd64
    build: ./buildlocal/amd64
    volumes:
      - ./app/data/files:/arozos/src/files
      - ./app/data/tmp:/arozos/src/tmp
      - ./app/data/system:/system
    ports:
      - "8888:80"
      - "2121:21"
    restart: always
  arm64:
    platform: linux/arm64
    build: ./buildlocal/arm64
    volumes:
      - ./app/data/files:/arozos/src/files
      -./app/data/tmp:/arozos/src/tmp
      -./app/data/system:/system
    ports:
      - "8888:80"
      -"2121:21"
    restart: always
