version: "2"
services:
  app:
    build: ./buildlocal
    volumes:
      - ./app/data/files:/arozos/src/files
      - ./app/data/tmp:/arozos/src/tmp
      - ./app/data/system:/system
    ports:
      - "8888:80"
      - "2121:21"
    restart: always
