# FROM ghcr.io/dwilliamhouston/aroz-dockerize:master@sha256:213e1d1029da8d142e4492ad67ef74c5ebbbac9c2c99400d91e719c39c2df75b
FROM ghcr.io/saren-arterius/aroz-dockerize:master
CMD /arozos/src/arozos -port 80
